name: build-deploy

on: 
  push: 
      branches:
      - master

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker-action
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: "${{ github.repository }}"
          tags: "${{ github.sha }}"
      - name: wechat-work-bot-success-build
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [构建容器成功](https://github.com/${{github.repository}}) \n
          > registry: ${{ secrets.DOCKER_REGISTRY }} \n
          > repo: ${{ github.repository }} \n 
          > tag: ${{ github.sha }} \n
          > full: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
          "
      - name: wechat-work-bot-failed-build
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ❎ ${{ github.event.repository.name }} 镜像构建失败 \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          " 
  deploy:
    needs: build
    name: k8s-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set-deployment-config
        run: |
          XIMAGE="${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}"
          sed -i "s#HAPPYIMAGE#$XIMAGE#g" ./chart/config.yaml
          sed -i "s#HAPPYREPO#${{ github.event.repository.name }}#g" ./chart/config.yaml
          sed -i "s#BOT_API#${{ secrets.BOT_API }}#g" ./chart/config.yaml

      - name: k3s-apply-deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ./chart/config.yaml
      - name: wechat-work-bot-success-deploy
        if: ${{ success() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ⭕ 正在滚动更新 ${{ github.event.repository.name }}\n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          "
      - name: wechat-work-bot-failed-deploy
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ❎ k8s部署 ${{ github.event.repository.name }} 失败\n
          > link: [项目地址](https://github.com/${{github.repository}})   \n" 